### ISSUE TITLE
Is railgun already taken down?

### ISSUE THREAD

**Issue by sanslash332** [ComputerMaster1st/Railgun#66]
Hello guys,

I ask that because on my server I see railgun connected, but she doesn't answer any command; atmost any command with the old format.
She has online status and her classic status message of use rghelp for help, but she doesn't say nothing.
And you can't re-add her, because she is currently on 100 servers.

I only ask just to know the future  of the project.

Thanks.

**Comment by ComputerMaster1st** [comment]
Hellew~

Here's an announcement from my Discord:

<===== ===== =====>

@everyone **Server Issues & Early Access To @Railgun#2398**

Hellew everynyaaa~!

We had to do an unscheduled reboot of Neko-01 server due to system updates and issues with server software. At this time, we're currently recompiling MongoDB which is why @Cryzen#3071 is even more dead now for the time being until MongoDB is fixed. I will ping once Cryzen is kinda back online again for music.

As for @Railgun#2398, it is now live but is **VERY EARLY ACCESS!** Please **do not** expect any music functionality with Railgun at this time. At the moment, we have Role-Request, Bites, RST, Dice, Magic 8 ball, etc. When using the bot, type "/" and you should see the commands pop up. For any questions, please use #mega-forum with the tag "Railgun".

I will be programming Railgun a bit more often as I need to get things done for it but will also be taking it very slow as I want to make sure everything is working before I move on to the next piece of the puzzle. Be ready for more programming streams in future and more headaches.

For those who wish to support Railgun to keep the server(s), feel free to visit my Patreon: https://www.patreon.com/nekoputer

Thank you~

Bot Invite URL: https://discord.com/api/oauth2/authorize?client_id=958570576635625502&permissions=0&scope=bot%20applications.commands
Or click on "Add To Server" when you check Railgun's profile.

**Comment by sanslash332** [comment]
O, thanks @ComputerMaster1st 
For the answer!

Sorry for not read the anounsement; I have to get into your discord server. Sorry for that.

So, about the classic crysen, seeing that it has problems with the message intent, what are the plans for  it? Simply drop it and wait to the new bot that will be verified? So It will don't has problem with the messages?
Or you will try to revive the old crysen :-)

Thanks for your answers!

**Comment by ComputerMaster1st** [comment]
The new bot has already deployed but has no music functions yet sadly. Cryzen will still stay online for those who have Auto-Join still configured at this time.

**Comment by sanslash332** [comment]
Oki, thanks for the information!

Waitrin for news about the bots. :-) thanks!
